name: Playwright Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 9.1.3

    - uses: actions/setup-node@v5
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2t64
        pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install chromium

    - name: Build Chromium extension
      run: pnpm vite build -c vite.config.chromium.ts

    - name: Run Playwright tests
      run: pnpm test:e2e --reporter github
