name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.3

      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Run test
        run: pnpm test
